### ISSUE TITLE
it tries to do something with Python :)

### ISSUE THREAD

**Issue by michaud** [code-biscuits/js-ts-biscuits#5]
not very helpful but two meh's, right? ;)
![image](https://user-images.githubusercontent.com/338436/95642257-aa6cb800-0aa7-11eb-82b3-d0146f0de596.png)

**Comment by cmgriffing** [comment]
Good catch. I will scope it to just relevant file types and that should fix it.

**Comment by cmgriffing** [comment]
I believe version 0.0.9 fixes this. Can you please confirm and close if so?

**Comment by michaud** [comment]
python files no longer have annotations
